# House Price Prediction

# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import pandas_profiling
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,accuracy_score,mean_squared_error,mean_absolute_error
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import RobustScaler

## Reading Dataset

In [2]:
df=pd.read_csv("ML2 Linear Regression Home Price Prediction.csv")

In [3]:
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,03/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,04/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,04/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,13 Burns St,4,h,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

### Getting Information About Data set

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object
 6   SellerG        34857 non-null  object
 7   Date           34857 non-null  object
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object
 17  Lattitude      26881 non-null  float64
 18  Longtitude     26881 non-null  float64
 19  Regionname     34854 non-null  object
 20  Propertycount  34854 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 5.6+ MB

In [5]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [6]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,34857.000000,2.724700e+04,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,13742.00000,15551.000000,26881.000000,26881.000000,34854.000000
mean,3.031012,1.050173e+06,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,160.25640,1965.289885,-37.810634,145.001851,7572.888306
std,0.969933,6.414671e+05,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,401.26706,37.328178,0.090279,0.120169,4428.090313
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1196.000000,-38.190430,144.423790,83.000000
25%,2.000000,6.350000e+05,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,102.00000,1940.000000,-37.862950,144.933500,4385.000000
50%,3.000000,8.700000e+05,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,136.00000,1970.000000,-37.807600,145.007800,6763.000000
75%,4.000000,1.295000e+06,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,188.00000,2000.000000,-37.754100,145.071900,10412.000000
max,16.000000,1.120000e+07,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,44515.00000,2106.000000,-37.390200,145.526350,21650.000000

<h1>Cleaning</h1>

In [7]:
df.drop(["Date","Address","Postcode","YearBuilt","Lattitude","Longtitude"],axis=1,inplace=True)

In [8]:
df.head()

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,Yarra City Council,Northern Metropolitan,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3.0,2.0,1.0,0.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,Yarra City Council,Northern Metropolitan,4019.0

#### Checking For Null Values

In [9]:
df.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Distance             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
CouncilArea          3
Regionname           3
Propertycount        3
dtype: int64

#### Filling Null Values

In [10]:
for i in ("Propertycount","Distance","Bedroom2"
         ,"Bathroom","Car"):
    df[i]=df[i].fillna(0)

In [11]:
for i in ("Landsize","BuildingArea"):
    df[i]=df[i].fillna(df[i].mean())

In [12]:
df.shape

(34857, 15)

In [13]:
df.isnull().sum()

Suburb              0
Rooms               0
Type                0
Price            7610
Method              0
SellerG             0
Distance            0
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
CouncilArea         3
Regionname          3
Propertycount       0
dtype: int64

In [14]:
df=df.dropna()

In [15]:
df.shape

(27244, 15)

In [16]:
df.isnull().sum()

Suburb           0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Distance         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
CouncilArea      0
Regionname       0
Propertycount    0
dtype: int64

In [17]:
df.shape

(27244, 15)

#### Checking For Unique Values

In [18]:
df["Method"].unique()

array(['S', 'SP', 'PI', 'VB', 'SA'], dtype=object)

In [19]:
df['Regionname'].unique()

array(['Northern Metropolitan', 'Western Metropolitan',
       'Southern Metropolitan', 'Eastern Metropolitan',
       'South-Eastern Metropolitan', 'Eastern Victoria',
       'Northern Victoria', 'Western Victoria'], dtype=object)

In [20]:
df

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.000000,79.0000,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.000000,150.0000,Yarra City Council,Northern Metropolitan,4019.0
5,Abbotsford,3,h,850000.0,PI,Biggin,2.5,3.0,2.0,1.0,94.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
6,Abbotsford,4,h,1600000.0,VB,Nelson,2.5,3.0,1.0,2.0,120.000000,142.0000,Yarra City Council,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.000000,160.2564,Maribyrnong City Council,Western Metropolitan,6543.0
34853,Yarraville,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.000000,104.0000,Maribyrnong City Council,Western Metropolitan,6543.0
34854,Yarraville,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.000000,120.0000,Maribyrnong City Council,Western Metropolitan,6543.0
34855,Yarraville,3,h,1140000.0,SP,hockingstuart,6.3,0.0,0.0,0.0,593.598993,160.2564,Maribyrnong City Council,Western Metropolitan,6543.0
34856,Yarraville,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.000000,103.0000,Maribyrnong City Council,Western Metropolitan,6543.0

## Encoding Features

### OneHotEncoding

In [21]:
df

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.000000,79.0000,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.000000,150.0000,Yarra City Council,Northern Metropolitan,4019.0
5,Abbotsford,3,h,850000.0,PI,Biggin,2.5,3.0,2.0,1.0,94.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
6,Abbotsford,4,h,1600000.0,VB,Nelson,2.5,3.0,1.0,2.0,120.000000,142.0000,Yarra City Council,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.000000,160.2564,Maribyrnong City Council,Western Metropolitan,6543.0
34853,Yarraville,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.000000,104.0000,Maribyrnong City Council,Western Metropolitan,6543.0
34854,Yarraville,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.000000,120.0000,Maribyrnong City Council,Western Metropolitan,6543.0
34855,Yarraville,3,h,1140000.0,SP,hockingstuart,6.3,0.0,0.0,0.0,593.598993,160.2564,Maribyrnong City Council,Western Metropolitan,6543.0
34856,Yarraville,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.000000,103.0000,Maribyrnong City Council,Western Metropolitan,6543.0

In [22]:
df=pd.get_dummies(df,drop_first=True)
df

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Propertycount,Suburb_Aberfeldie,...,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
1,2,1480000.0,2.5,2.0,1.0,1.0,202.000000,160.2564,4019.0,0,...,0,1,0,0,1,0,0,0,0,0
2,2,1035000.0,2.5,2.0,1.0,0.0,156.000000,79.0000,4019.0,0,...,0,1,0,0,1,0,0,0,0,0
4,3,1465000.0,2.5,3.0,2.0,0.0,134.000000,150.0000,4019.0,0,...,0,1,0,0,1,0,0,0,0,0
5,3,850000.0,2.5,3.0,2.0,1.0,94.000000,160.2564,4019.0,0,...,0,1,0,0,1,0,0,0,0,0
6,4,1600000.0,2.5,3.0,1.0,2.0,120.000000,142.0000,4019.0,0,...,0,1,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,1480000.0,6.3,4.0,1.0,3.0,593.000000,160.2564,6543.0,0,...,0,0,0,0,0,0,0,0,1,0
34853,2,888000.0,6.3,2.0,2.0,1.0,98.000000,104.0000,6543.0,0,...,0,0,0,0,0,0,0,0,1,0
34854,2,705000.0,6.3,2.0,1.0,2.0,220.000000,120.0000,6543.0,0,...,0,0,0,0,0,0,0,0,1,0
34855,3,1140000.0,6.3,0.0,0.0,0.0,593.598993,160.2564,6543.0,0,...,0,0,0,0,0,0,0,0,1,0
34856,2,1020000.0,6.3,2.0,1.0,0.0,250.000000,103.0000,6543.0,0,...,0,0,0,0,0,0,0,0,1,0

#### Defining Objects For Features & Target

In [23]:
features=df.drop("Price",axis=1)

In [24]:
features.columns

Index(['Rooms', 'Distance', 'Bedroom2', 'Bathroom', 'Car', 'Landsize',
       'BuildingArea', 'Propertycount', 'Suburb_Aberfeldie',
       'Suburb_Airport West',
       ...
       'CouncilArea_Wyndham City Council', 'CouncilArea_Yarra City Council',
       'CouncilArea_Yarra Ranges Shire Council', 'Regionname_Eastern Victoria',
       'Regionname_Northern Metropolitan', 'Regionname_Northern Victoria',
       'Regionname_South-Eastern Metropolitan',
       'Regionname_Southern Metropolitan', 'Regionname_Western Metropolitan',
       'Regionname_Western Victoria'],
      dtype='object', length=744)

In [25]:
target=df["Price"]

In [26]:
features_train, features_test, target_train, target_test = train_test_split(features,target, test_size=0.2,random_state=12)

## Model Selection

### Linear Regression & OneHotEncoding

In [27]:
model=LinearRegression()

In [28]:
model.fit(features_train,target_train)

LinearRegression()

In [29]:
predicted_price=model.predict(features_test)
predicted_price

array([ 758706.88764302, 1427162.36420051,  992469.94089202, ...,
        885010.92773061,  690388.18342351,  725741.27250498])

### Checking For Over Fitting or Under Fitting

In [30]:
model.score(features_train,target_train)

0.6860073002004154

In [31]:
model.score(features_test,target_test)

0.6444872827061818

### Model is Under Fitted

## Checking Accuracy of Model

In [32]:
model.intercept_

811889.0613046023

In [33]:
model.coef_

array([ 2.65385521e+05, -4.87015132e+04, -9.15012610e+04,  1.33328825e+05,
        4.51421134e+04,  2.36402562e+00,  3.34369853e+01,  8.72947285e-01,
        2.40052521e+05, -4.86468479e+04, -8.16998222e+04,  2.99713867e+05,
        8.90244701e+04,  1.85437791e+05,  1.74573503e+05, -7.14126477e+04,
       -1.74424823e+05, -6.82169972e+04,  9.79856801e+04, -1.30055291e+05,
       -6.44904571e+04,  4.89147205e+03,  8.66001233e+04, -2.47109797e+05,
       -1.43255952e+05, -2.27755371e+05,  1.10016085e+05, -1.26987375e+05,
        1.79106082e+05,  1.53226902e+03,  1.28382731e+05,  5.23473516e+03,
        2.10309192e+05,  5.73169543e+04,  1.84473887e+05, -3.73639881e+05,
        1.06445055e+05,  1.87914261e+03,  6.66163012e+03,  2.10047147e+05,
        1.44861648e+05, -1.25013664e+05, -8.31369285e+04,  3.23653563e+05,
        1.64916067e+05,  2.88159849e+05,  1.97149365e+05, -1.38857397e+05,
       -7.83656755e+04,  3.78328019e+05, -1.08449468e+05, -7.54710743e+04,
       -2.43146470e+04,  7.45033473e+04,  5.21435689e+04,  2.78511960e+04,
       -2.61970421e+04,  1.53827560e+05, -2.12130437e+05,  1.17277135e+05,
       -1.57265128e+05,  1.71516511e+03, -1.64565826e+05, -2.51794927e+05,
       -4.37632035e+04,  1.65648390e+03, -1.08722124e+05,  7.57912620e+04,
       -1.69757091e+05,  5.04260146e+05,  6.73071476e+04,  2.91157280e+05,
        8.58165311e+03, -1.66042207e+05,  4.01862302e+05, -1.25439586e+05,
       -2.04767030e+05, -2.34315579e+04,  1.29945348e+04,  1.94514512e+04,
       -6.83721995e+04,  3.32396060e+05, -3.32632484e+04, -2.15776695e+05,
       -1.66444765e+05, -3.35201583e+05, -2.74320004e+04, -2.13957863e+05,
        1.64215226e+05,  2.28847506e+05, -1.03276697e+05, -2.29761601e+05,
        2.88611045e-06,  5.34809587e+04, -1.01010685e+05, -1.47997160e+04,
       -6.51429348e+04,  3.76542293e+04, -7.51880993e+04, -1.50870447e+04,
        2.21302346e+04,  6.08245011e+04, -6.29234112e+04,  3.05481284e+04,
        4.88095164e+04, -3.51250210e+05,  1.37214668e+05, -4.90897181e+04,
        1.44684116e+04,  4.46131550e+05, -7.06364655e+04,  4.80301457e+04,
       -1.63043435e+05, -2.69324767e+05,  2.59043151e+05, -1.91165719e+05,
       -3.12137036e+05,  1.17808940e+04,  2.31053283e+04,  1.12403370e+05,
       -3.89429806e+05, -9.16012342e+04,  2.59313501e+05,  4.03422830e+05,
        2.59777138e+05,  8.76278341e+04, -1.74491873e+04, -1.72181831e+05,
        4.59301322e+04, -3.86741062e+05, -1.94893031e+05, -1.49410453e+04,
        1.26374394e+05,  4.93340091e+04, -2.69932646e+04, -1.63324328e+05,
        9.98908705e+04,  1.20932189e+05, -9.49234738e+04,  1.91706710e+05,
       -8.46802271e+03,  2.47075437e+05,  2.36357211e+05, -6.00726078e+04,
       -4.54779669e+04, -6.94390733e+04,  2.53816149e+05, -6.17352337e+04,
        3.86887690e+05, -2.54325832e+05,  1.13923865e+05,  9.36951370e+04,
       -3.18303995e+05, -3.88984033e+04, -9.43978746e+04,  3.15554362e+05,
       -4.49561283e+04, -2.28471601e+05,  5.85376681e+04,  3.74301556e+04,
       -1.20388011e+05,  1.58689643e+05,  1.33354495e+05, -2.36699059e+05,
       -4.00705607e+04, -2.98386740e+05, -1.80889824e+05,  4.74923817e+05,
       -1.25682549e+05,  4.51149184e+04, -1.46614360e+05, -4.05816112e+05,
       -4.87873716e+05, -1.05236089e+05,  7.49172091e+03, -3.57467040e+03,
        7.41489503e+04, -1.58653760e+05, -1.11329655e+05, -4.34438013e+04,
        4.47664333e+05, -1.47497665e+05,  2.26076122e+05, -1.52288836e+05,
        4.56917870e+04, -2.64724150e+04,  7.20498037e+04,  1.17742490e+05,
       -9.25504707e+03, -6.51409793e+04, -1.00449617e+05, -1.52487648e+05,
        3.13721205e+04,  1.41449425e+05, -9.71216214e+04, -7.93408471e+04,
        4.06955424e+04,  1.16249278e+04, -2.28501749e+05, -5.38074891e+04,
       -9.43660792e+04,  1.06892780e+05, -3.62392350e+04, -1.17479041e+05,
        8.81981140e+03,  8.74637748e+04,  8.02342291e+04,  5.12055101e+04,
       -7.62092724e+04,  4.75365084e+05,  3.08997710e+04,  2.22557081e+03,
        2.50067775e+05, -2.64499586e+04, -2.99106281e+03,  1.23440846e+04,
        3.89293712e+04, -9.07941163e+04,  9.10776997e+04,  1.57685716e+05,
        3.03686573e+04,  5.27318712e+05, -7.12169988e+04,  8.56709761e+04,
       -2.60086381e-07,  2.57006831e+04, -2.75928398e+04, -3.00003340e+05,
        5.19109183e+04, -1.26121510e+05, -1.93870026e+05,  1.35344025e+05,
       -2.88691489e+04,  2.08288951e+05, -1.66012983e+05,  6.64265438e+03,
        6.55730742e+04, -4.86664154e+04, -7.18571302e+04,  8.14632883e+04,
       -2.02576843e+04, -2.81734579e+04,  4.74324947e+05,  1.62176848e+05,
        1.07081757e+05,  1.58661357e+04,  5.65177187e+04,  7.67834165e+03,
       -5.10336130e+04, -3.90122427e+05,  1.18189367e+05,  1.17895115e+05,
        2.89579938e+05,  2.02471063e+05,  1.45721174e+05, -2.57942006e+04,
        2.11571283e+05,  4.09275434e+05,  2.35875280e+05, -1.85121708e+05,
       -7.97527028e+04, -2.61061535e+05, -5.91969034e+04,  5.06739091e+05,
        1.16559634e+05, -5.87032968e+04,  6.04509311e+04,  2.44051188e+05,
        3.67013420e+04,  1.16490572e+05, -9.64127061e+04, -1.31945218e+05,
        2.60670201e+05, -2.49899041e+05, -1.69807482e+05, -6.89850387e+04,
       -1.66965704e+05,  1.85302875e+05,  6.98898788e+04, -1.74593615e+05,
        1.48809243e+05,  1.00473946e+05,  3.27968939e+04,  2.62572438e+05,
       -1.78885074e+05, -8.08596718e+04, -2.44880846e+05, -5.88116819e+04,
       -7.09303297e+04, -3.94168393e+05, -6.91577870e+04, -2.02020490e+04,
       -6.33674983e+04,  5.17786374e+04, -3.40259847e+05, -1.41871158e+05,
        6.50678297e+04, -2.31919613e+05,  4.58699281e+05,  5.67767194e+04,
       -5.27439280e+04, -1.30411184e+05, -2.54789575e+04,  1.12454698e+05,
       -6.12951500e+04, -7.15669437e+04, -3.75024458e+04, -3.83562170e+04,
        1.21979775e+05, -2.04505580e+05,  2.24062054e+05, -4.93782058e+04,
        5.67228172e+04,  1.38786341e+05,  2.69650665e+04,  2.00897132e+04,
        9.22617595e+04,  1.39686904e+04, -4.01184134e+04, -7.10324474e+04,
       -4.09726575e+05,  1.93816028e+05,  2.26572419e+05, -3.49729418e+05,
       -2.70765396e+05,  2.33864292e+05, -2.93534541e+05, -2.17182839e+05,
        5.89092829e+04, -1.03227714e+05, -2.77467558e+05, -2.01911256e+05,
       -6.14987692e+04, -7.02155110e+04,  7.93211670e+04, -8.99301457e+04,
       -1.76412788e+05,  1.28432285e+04,  3.92698483e+05, -4.46669199e+04,
        2.80540718e+05, -5.49979404e+03, -1.70410966e+05,  1.54134097e+05,
        8.74341031e+04,  3.75020738e+05, -1.03703364e+05, -5.88066337e+04,
        5.36751306e+04,  1.10990067e+04, -1.09033941e+05, -2.72075904e+05,
       -4.70540754e+05,  7.80284324e+04,  8.15889698e+04,  4.62964125e+04,
        1.31622631e+04, -7.22958305e+04,  3.19370323e+04,  7.38091285e+05,
        2.60807401e+05, -2.74086908e+05,  4.81853872e+05,  9.70252691e+04,
       -9.20729945e+04, -8.11116526e+04,  1.41487823e+05, -1.81778214e+05,
        1.75523791e+05,  2.01041895e+05, -7.02415540e+04, -9.47283461e+04,
        3.65852843e+04,  5.43365528e+05,  2.37690983e-07, -4.01272181e+04,
        3.22893719e+05,  1.28240582e+05,  7.95448949e+04,  4.17945985e+05,
       -4.91060453e+04, -1.34596039e+03, -5.23000894e+04,  7.99125915e+04,
        2.13261101e+05,  9.11700307e+04, -1.62986881e+05, -2.67138270e+04,
        7.12426032e+04,  1.79235114e+05,  9.90831056e+04,  8.43979610e+05,
        1.41385094e+05,  4.00532651e+05, -6.02368387e+04, -1.86144201e+05,
       -4.45402983e+04,  7.74062640e+04,  1.37991386e+05,  8.13864146e+04,
        9.60339928e+03,  1.74559750e+05, -5.97210601e-07,  7.61228875e-07,
        9.03875244e+04, -1.34034719e+03,  3.37159678e+05,  3.55577357e+05,
       -8.99213993e+04,  4.09118559e+04,  2.55589839e-07,  4.01856719e+05,
        9.00883130e+04,  2.32792081e-06,  1.32430986e+05,  3.47218965e+05,
        1.45083732e+05, -2.44604824e+05,  1.45470466e+05, -3.13863639e+05,
        1.57522481e+05, -2.33762740e+05,  1.02402642e+05, -1.42124642e+05,
        2.51910573e+05,  8.57288484e+04,  1.81505792e+05,  1.34468571e+05,
        4.40120854e+05,  2.09504866e+05,  3.74723778e+05, -2.65211470e+04,
       -1.55021561e+05,  5.13240874e+04,  5.91781550e+04,  8.58215382e+04,
        8.55814666e+04,  6.12641533e+03,  1.39062295e+06,  1.65163593e+05,
       -1.22181443e+05,  6.22046403e+04,  2.26622952e+03, -6.08735351e+05,
       -7.08630678e+04, -1.01621510e+04, -4.32488430e+04,  6.21261739e+04,
        1.03816962e+05,  4.06287885e+05, -4.81110569e+03,  8.70287132e+04,
        1.20571972e+05,  1.19073546e+05,  1.92320689e+05,  7.69035608e+04,
       -2.39897592e+04, -5.59115320e+04,  4.41782082e+04,  1.54701231e+06,
        7.49546310e+04,  1.58593432e+05,  5.70084957e+04,  1.08693535e+05,
        4.17153728e+04, -2.38889583e+05, -1.40508930e+05,  3.99140356e+04,
       -1.00757461e-06, -1.86069529e+05, -2.55514476e+04,  1.65252383e+05,
        7.45346687e+04,  5.82576435e+05,  7.83397894e+04,  1.69359543e+04,
       -1.01976500e+05, -2.03489798e+05,  7.45159659e+04, -6.92413968e+04,
        8.53352635e+03, -2.83412179e+04,  1.85011344e+04,  3.39155618e+04,
        2.78472942e+05, -4.19530725e+04,  6.53273394e+05,  1.05643543e+05,
        1.32430442e+05,  2.11054907e+05,  5.52985808e+04,  4.85718666e+03,
       -2.01691365e+04,  1.40323630e+02,  1.37161130e+05,  5.51329613e+04,
        1.28565038e+05,  7.45914005e+04,  1.45695430e+05, -1.29358705e-06,
        4.43833414e-07, -5.19470136e+05,  2.20575497e+05,  1.49769028e+05,
       -1.64852265e+05,  7.90815386e+03,  1.19650213e-06,  5.71211110e+05,
        8.65708687e+05,  1.21849342e+05,  4.11207932e+05, -1.96467644e+04,
        7.96236673e+04, -7.82547730e+04,  4.59335903e+04, -2.85517898e+04,
        5.51639650e+05, -1.51758338e+05,  1.45262755e+05,  4.39965096e+04,
       -4.95274287e+04,  1.17526619e+05,  3.15377386e+04, -2.78619191e+04,
        2.47058392e+05,  1.10053060e+05,  2.26418019e+04, -8.80158041e-07,
        2.17489582e+04,  1.34109714e+05, -6.18506590e+03,  2.64763358e+03,
       -8.39761867e+04, -1.36190873e+05,  2.55522810e+04,  1.06152018e+05,
        3.91391972e+05, -1.69647611e+04,  1.26157795e+05,  2.99146578e+05,
        1.76054823e+05, -9.03638713e+03,  1.13566038e+05, -1.96117693e+05,
       -1.81465352e+04, -3.45222645e+04,  1.88377913e+05,  6.82940916e+04,
       -7.14362351e+04,  1.91047187e+05,  1.31229707e+05, -2.67149321e+04,
        1.68610239e+05,  7.37272556e+04,  6.92772639e+05,  2.50444105e+05,
        7.69322140e+04, -1.65433553e+05,  1.16390473e+05,  1.03472612e+05,
        1.48142335e+05, -5.20691830e+04,  7.41753369e+04, -6.52881127e+04,
        1.47571715e+05,  1.16473529e-07,  3.28421340e+05, -1.05223580e+04,
        1.98687161e+05,  5.52613728e+04,  2.55167229e+05,  5.73528927e+04,
       -1.99315078e+05,  1.49893146e+05,  3.35857700e+05,  9.60325955e+04,
       -6.04159605e+03,  8.82996075e+04,  3.50265760e+04,  4.59584462e+04,
       -2.65159488e+05,  2.49023905e+03,  1.63684124e+04, -1.97953903e+04,
        2.70098235e+05,  6.25920747e+04,  7.94362826e+04,  3.35080455e+05,
        2.20433643e+05,  2.69550118e+05,  3.74469806e+05,  2.55568713e+04,
        1.35234066e+05,  9.54053453e+04,  1.16865458e+05, -9.69900023e+04,
        2.34397758e+05,  7.71596505e+04, -5.07853014e+04,  1.78155404e+05,
       -5.58502247e+05, -3.41898310e+05, -1.08451685e+04,  4.07574123e+04,
        2.86540607e+04,  7.96744798e+04, -3.84978584e+04,  2.90319420e+05,
        4.32731199e+04,  4.59781597e+04, -1.98581732e+04,  3.60942907e+04,
       -4.80018172e+04, -4.78540927e+05,  4.47439888e+05,  2.42599936e+05,
        4.19730255e+04,  1.15477998e+05,  3.32991312e+04,  4.84799059e+04,
        4.27680789e-07,  4.20566464e+03, -7.88152536e+04,  3.71423005e+05,
       -1.77267926e+05,  3.67875402e+05, -4.00334050e+05,  6.69011240e+04,
        1.29456906e+05,  1.65609753e+05,  5.99306077e-07, -6.96803909e-07,
       -9.88191459e-07,  7.23514344e+04, -1.03155570e+05, -2.31257473e+05,
        3.10410365e+04,  4.82197098e+04, -4.23541375e+05,  4.32881322e+05,
        1.21106141e+05,  1.87158126e+05,  4.75458680e+03, -8.33818953e+04,
        5.56882810e+04, -2.62344872e+05,  7.86132810e+04, -3.33784828e+04,
        1.21957577e+05, -6.55651093e-07, -1.05132867e+05,  1.33192680e+05,
       -7.09958693e+04, -6.07729240e+04, -5.22975265e+05, -5.95302882e+04,
        1.46571715e+05,  1.25400727e+05, -1.07739058e+05,  7.08796005e+04,
        3.37718166e+05,  2.19221305e+05, -2.16644428e+03,  4.56194424e+05,
       -1.07139991e+05, -4.10655048e-07, -6.30837652e+04, -6.15254976e-08,
        9.68562921e+04,  1.14195102e+04,  6.62795764e+05,  4.79093930e+04,
        5.39846946e+04,  9.28829868e+05,  2.14206897e+05, -4.54543624e-07,
       -5.66639260e+04,  2.67209472e+05,  7.01306426e+04,  5.57022891e+04,
        1.31402317e+05,  1.69659409e+05,  4.71976807e+04,  1.50268290e+05,
        6.01251427e+04, -1.40207703e-07, -2.63880007e+05,  7.75552754e+04,
        5.98627842e+04,  1.87907909e+05,  2.85150222e+04,  1.81320758e+05,
        2.59393169e+05, -7.37332634e+04,  0.00000000e+00, -5.54370175e+04,
        6.64627089e+05,  1.31755954e+05,  2.41811518e+05,  5.46584402e+04,
        2.16987929e+03, -2.34356410e+05,  1.24900183e+05,  1.32927460e+05,
       -3.25002567e+04,  4.25345113e+05,  3.15940875e+05, -2.30308743e+05,
        2.88654388e+05,  2.27742473e+05, -5.00969932e+03,  3.63380265e+05,
        9.01623925e+04,  1.56698390e+04, -1.28456537e+05, -4.34915946e+04,
        1.64945722e+05,  8.05143010e+04,  5.20280910e+05,  9.33851744e+04,
       -2.01367010e+05,  9.96957796e+04, -2.64369702e+04, -1.55086637e+05,
        1.93816028e+05,  2.59632856e+04, -2.42023603e+04,  1.24484497e+05,
       -7.29372887e+04, -4.73917702e+04,  5.68671485e+04,  2.53473592e+05,
        8.07163599e+04,  3.59490311e+04, -1.83047735e+05, -6.33480906e+04,
        6.57401693e+04,  3.06378161e+05, -2.44166004e+05,  3.60179392e+05,
        1.57762101e+05,  4.95621017e+03, -1.87224217e+05,  2.51334176e+05])

In [34]:
print('Mean Squared Error ',mean_squared_error(target_test,predicted_price))

Mean Squared Error  157025962618.91278

In [35]:
print('Root Mean Squared Error ',np.sqrt(mean_squared_error(target_test,predicted_price)))

Root Mean Squared Error  396265.01563841436

In [36]:
print("Mean Absolute Error ",mean_absolute_error(target_test,predicted_price))

Mean Absolute Error  239373.62257406782

In [37]:
print('R2 Score ',r2_score(target_test,predicted_price))

R2 Score  0.6444872827061818

## Applying All Algorithm

In [38]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor,AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

In [39]:
models={'lr':LinearRegression(),
        'ls':Lasso(),
        'rg':Ridge(),
        'tree':DecisionTreeRegressor(),
        'rf':RandomForestRegressor(),
        'gb':GradientBoostingRegressor(),
        'knn':KNeighborsRegressor(),
        'svm':SVR(),
        'ad':AdaBoostRegressor(),
        'xbg':XGBRegressor()
       }

In [ ]:
for name, model in models.items():
    model1=model.fit(features_train,target_train)
    y_pred = model1.predict(features_test)
    print(f'{name} Mean squared error:  {mean_squared_error(target_test,y_pred)}') 
    print(f'{name} accuracy score: {model1.score(features_test,target_test)}\n')

lr Mean squared error:  157025962618.91278
lr accuracy score: 0.6444872827061818

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1384356087275143.0, tolerance: 880315882353.9323
  model = cd_fast.enet_coordinate_descent(

ls Mean squared error:  156976928982.19083
ls accuracy score: 0.6445982967139234

rg Mean squared error:  156682998063.49863
rg accuracy score: 0.6452637674288175

tree Mean squared error:  201635569292.54245
tree accuracy score: 0.5434894462882671

rf Mean squared error:  121406285306.47415
rf accuracy score: 0.7251315790968782

gb Mean squared error:  132650668205.43439
gb accuracy score: 0.6996738710081649

knn Mean squared error:  231379239076.53442
knn accuracy score: 0.4761486531427429

## Random forest gives best Accuracy